# Generated by Django 3.2.15 on 2023-08-02 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230803_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorderitem',
            options={'verbose_name': 'товары в заказе', 'verbose_name_plural': 'товары в заказах'},
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
