# Generated by Django 3.2.15 on 2023-08-04 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_remove_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorderitem',
            options={'verbose_name': 'товар в заказе', 'verbose_name_plural': 'товары в заказах'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.AlterField(
            model_name='productorderitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='количество'),
        ),
    ]
