# Generated by Django 3.2.15 on 2023-08-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230804_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_processing', 'В обработке'), ('on_assembly', 'На сборке'), ('in_delivery', 'В доставке'), ('delivered', 'Доставлен')], db_index=True, default='in_processing', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='productorderitem',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='foodcartapp.order', verbose_name='заказ'),
        ),
    ]
