# Generated by Django 3.2.15 on 2023-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличными при доставке'), ('ONLINE', 'Электронно при создании')], db_index=True, default='CASH', max_length=20, verbose_name='Cпособ оплаты'),
        ),
    ]
