# Generated by Django 3.2.15 on 2023-08-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20230825_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес доставки')),
                ('lat', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Широта')),
                ('lon', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
