# Generated by Django 3.2.15 on 2023-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20230828_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличными при доставке'), ('online', 'Электронно при создании')], db_index=True, max_length=20, verbose_name='Cпособ оплаты'),
        ),
    ]
