# Generated by Django 3.2.15 on 2023-08-25 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='updated_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
